name: 'Build, Scan, and Push Docker Image'
description: 'Builds, scans, and pushes a Docker image'
inputs:
   dockerfile:
     description: 'Path to the Dockerfile'
     required: true
   image-name:
     description: 'Name of the Docker image'
     required: true
   dockerhub-username:
     description: 'DockerHub username'
     required: true
   dockerhub-token:
     description: 'DockerHub token'
     required: true
   github-sha:
     description: 'GitHub SHA for tagging'
     required: true

runs:
  using: "composite"
  steps:
    - run: docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image-name }}-${{ inputs.github-sha }} .
      shell: bash
    - uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.image-name }}-${{ inputs.github-sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 0
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    - uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif' 
    - run: docker push ${{ inputs.image-name }}-${{ inputs.github-sha }}
      shell: bash
